# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
- job: infrastructure
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      version: '5.0.x'
  - task: Pulumi@1
    # condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))
    inputs:
      # Using a service connection is optional. Specify build variables for your pipeline or link variable groups
      # that contain the necessary environment variables needed by the Pulumi provider your Pulumi app uses.
      azureSubscription: 'teamceserviceconnection'
      command: 'preview'
      stack: 'pierskarsenbarg/azure-devops-csharp/dev'
  - task: Pulumi@1
    # condition: or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'BatchedCI'))
    inputs:
      # Using a service connection is optional. Specify build variables for your pipeline or link variable groups
      # that contain the necessary environment variables needed by the Pulumi provider your Pulumi app uses.
      azureSubscription: 'teamceserviceconnection'
      command: 'up'
      stack: 'pierskarsenbarg/azure-devops-csharp/dev'
      args: '--yes'
  - script: |
      echo "##vso[task.setvariable variable=resourceGroupName;isOutput=true]$(pulumi stack output ResourceGroupName)"
    displayName: 'Set stack outputs as variables'
    name: 'pulumi'
  # - script: echo $(pulumi.resourceGroupName)
  #   displayName: 'Run a one-line script'
